USE [master]
GO

DROP DATABASE [MercadoDatabase]
GO

CREATE DATABASE [MercadoDatabase]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MercadoDatabase', FILENAME = N'/var/opt/mssql/data/MercadoDatabase.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MercadoDatabase_log', FILENAME = N'/var/opt/mssql/data/MercadoDatabase_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MercadoDatabase].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MercadoDatabase] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MercadoDatabase] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MercadoDatabase] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MercadoDatabase] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MercadoDatabase] SET ARITHABORT OFF 
GO

ALTER DATABASE [MercadoDatabase] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MercadoDatabase] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MercadoDatabase] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MercadoDatabase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MercadoDatabase] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MercadoDatabase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MercadoDatabase] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MercadoDatabase] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MercadoDatabase] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MercadoDatabase] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MercadoDatabase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MercadoDatabase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MercadoDatabase] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MercadoDatabase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MercadoDatabase] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MercadoDatabase] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MercadoDatabase] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MercadoDatabase] SET RECOVERY FULL 
GO

ALTER DATABASE [MercadoDatabase] SET  MULTI_USER 
GO

ALTER DATABASE [MercadoDatabase] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MercadoDatabase] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MercadoDatabase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MercadoDatabase] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [MercadoDatabase] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MercadoDatabase] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [MercadoDatabase] SET QUERY_STORE = ON
GO

ALTER DATABASE [MercadoDatabase] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [MercadoDatabase] SET  READ_WRITE 
GO


